### ISSUE TITLE
Q2 Seemingly Incorrect Answer

### ISSUE THREAD

**Issue by roberthenrymueller** [mids-w203/practice_test_1#1]
I think there is an error in the answers for Q2 on the practice test 1. The final formula references (1/4 * 6/4), but i believe it should be (1/4*10/4). Final answer would then be 6.25, not 6.

**Comment by RERobbins** [comment]
I was about to raise the very same issue.

**Comment by amy576** [comment]
+1 to this issue

**Comment by d-alex-hughes** [comment]
Thanks @roberthenrymueller , @RERobbins and @amy576 . I closed this with PR #5 that closes number 1.
