### ISSUE TITLE
Q3 (Roll those bones)

### ISSUE THREAD

**Issue by lindseyBang** [mids-w203/practice_test_1#2]
In Question 3, it looks like {2,2} is missing for A.
I think that A should be {1,1}, {1,2}, {2,1}, and {2,2} 
* P(A) = 4/16 = 1/4
* P(B) = 9/16
* 1/4*9/16 <> 1/16

**Comment by noriiii** [comment]
Yes, I also think it is missing {2,2} for event A. Therefore, P(A) = 1/4.

**Comment by d-alex-hughes** [comment]
Thanks! I'm on it.
