### ISSUE TITLE
Independent Thoughts part c uses incorrect joint density

### ISSUE THREAD

**Issue by amy576** [mids-w203/practice_test_1#3]
Independent Thoughts part c uses the wrong joint PDF function for all three variables and uses 2xyz instead of 8xyz, which is the correct joint PDF (as referenced earlier in the problem). The answer ends up being correct because it uses the alternative methodology of multiplying the univariate PDFs of each of the variables, since all 3 are independent.

**Comment by noriiii** [comment]
I also noticed the lower bound for the X2 integral is equal to 2. I think it should also be zero just like the lower bounds of the other two integrals.

**Comment by d-alex-hughes** [comment]
Thanks @amy576 and @noriiii . I'm on this.
